version: '3.7'

services:
  nginx:
    image: nginx:1.15.3-alpine
    restart: always
    depends_on:
      - php_fpm
    volumes:
      - './app/web:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'

  php_fpm:
    image: greenera/php-fpm7:latest
    working_dir: /usr/src/app
    volumes:
      - './app:/usr/src/app'
    command: bash -c 'composer install'
    restart: always
    depends_on:
      - my_mysql

  node:
    image: greenera/node10:latest
    volumes:
      - ./app:/usr/src/app
    restart: always
    working_dir: /usr/src/app
    command: bash -c "npm i what-input && npm install && npm run dev" #todo npm i what-input?

  my_mysql:
    image: greenera/mysql_5:latest
    restart: always
    command: --max_allowed_packet=500M #todo перевірити чи так працює, чи потібно ставити байти
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  phpmyadmin:
    depends_on:
      - my_mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: my_mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

#  adminer:
#    image: adminer
#    restart: on-failure
#    ports:
#      - '8080:8080'
